### ISSUE TITLE
Crash during siege

### ISSUE THREAD

**Issue by amatt13** [amatt13/PostMortemPossession#4]
The game might crash when taking control of on ally during a siege.

It is a Null Reference exception that gets thrown somewhere down in the engine within Native.dll.  I don't  have access to anything meaningful with the debugger as its all [extenal code] and calls to the Native library from which the decompiler can't show anything useful from.

I have not found a consistent way of recreating the exception. It happen to me twice while I played in the campaign, and once in a custom siege scenario. All three times happened when I used the "automatic ally control" (default key binding U).

**Comment by amatt13** [comment]
Possibly related:

Copied from [vpyagai's post ](https://forums.nexusmods.com/index.php?showtopic=8636748/#entry104919568) on the mod's Nexus page:

"[...] it occurred when I started to control one of my units during the siege.
My units seemed to be stuck at the top of the ladder, being already on the wall.

````
?Exception information
Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: TaleWorlds.MountAndBlade
CallStack:

at TaleWorlds.MountAndBlade.LadderQueueManager.RemoveAgentFromQueueAtIndex(Int32 queueIndex)
at TaleWorlds.MountAndBlade.LadderQueueManager.OnTick(Single dt)
at TaleWorlds.Engine.ManagedScriptHolder.TickComponents_Patch1(ManagedScriptHolder this, Single dt)
````


- Involved Modules
Bannerlord.ButterLib
````
Method: static System.Void Bannerlord.ButterLib.ExceptionHandler.BEWPatch::Finalizer(System.Exception __exception)
Frame: TaleWorlds.Engine.ManagedScriptHolder.TickComponents_Patch1 at offset 612 in file:line:column
````

**Comment by Keizer120** [comment]
Can confirm I can reproduce it all the time when my companion is about to take the ladder or already on it.

**Comment by amatt13** [comment]
About to take the ladder or when they are on it?
If so, it might be realted to what I'm doing to the agen't speed when we take control of them.

Thanks the info.

**Comment by Keizer120** [comment]
My companion was 2 Times on the ladder.
One time it was in front the ladder with maybe 3 soldiers in front.


Op ma 14 feb. 2022 20:39 schreef Anders Lykke Matthiassen <
***@***.***>:
